# Configuración para GitHub Pages
root: /
url: https://[TU-USUARIO].github.io/[TU-REPOSITORIO]

# Configuración del sitio
title: "Generador de Carnés CTP Sabalito"
description: "Aplicación web para generar carnés de transporte estudiantil"

# Configuración de Jekyll (GitHub Pages)
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
